"""Initial migration

Revision ID: 345887b42117
Revises: c3a72ce31474
Create Date: 2025-07-16 16:16:22.018583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345887b42117'
down_revision = 'c3a72ce31474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_search')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('settings')
        batch_op.drop_column('last_login')

    op.create_table('movie_search',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('movie_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('search_count', sa.INTEGER(), nullable=True),
    sa.Column('last_searched', sa.DATETIME(), nullable=True),
    sa.Column('tmdb_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
